language: ruby
rvm:
  - 2.4.1
bundler_args: --without development
# sudo: enabled
dist: trusty
install:
  - sudo apt-get update && sudo apt-get install -y libfontconfig google-chrome-stable
  - bundle install
script: bundle exec rails test
# env:
#   global:
#     - CI_NODE_TOTAL=2
#   matrix:
#     - CI_NODE_INDEX=0
#     - CI_NODE_INDEX=1
