development:
  clients:
    default:
      database: dcaf_case_management_development
      hosts:
        - <%= ENV['mongohost'] || 'localhost' %>:<%= ENV['mongoport'] || 27017 %>
      options:

test:
  clients:
    default:
      database: dcaf_case_management_test
      hosts:
        - <%= ENV['mongohost'] || 'localhost' %>:<%= ENV['mongoport'] || 27017 %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
        connect_timeout: 15
        wait_queue_timeout: 15

production: 
  clients:
    default:
      database: '<%= ENV['mongodb'] %>'
      hosts:
        - '<%= ENV['mongohost'] %>:<%= ENV['mongoport'] %>'
      options:
        user: '<%= ENV['mongouser'] %>'
        password: '<%= ENV['mongopass'] %>'
